on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: "True"
      with:
        go-version: '1.14.x'
    - name: Display a greeting
      uses: myitcvblog/myfirstgoaction@7096ad461380fef1c02fb53935bd26153465906b
      with:
        name: Helena
